# Generated by Django 3.2.3 on 2021-05-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='descriprion',
            new_name='description',
        ),
    ]
